micronaut:
  application:
    name: availability
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
  automatic-class-models: false
grpc:
  server:
    port: 8081
  channels:
    users:
      address: ${USERS_HOST:localhost}:${USERS_PORT:8080}
      plaintext: true
