micronaut:
  application:
    name: availability
  server:
    port: ${MANAGEMENT_PORT:8181}
mongodb:
  uri: ${MONGO_PROTOCOL:mongodb}://${MONGO_CREDENTIALS:}${MONGO_HOST:`localhost:27017`}
  automatic-class-models: false
redis:
  uri: ${REDIS_PROTOCOL:redis}://${REDIS_CREDENTIALS:}${REDIS_HOST:`localhost:6379`}
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  caches:
    users-availability:
      expire-after-write: 1h
grpc:
  server:
    port: ${SERVER_PORT:8081}
  channels:
    users:
      plaintext: true
      target: users:50051
tracing:
  zipkin:
    enabled: true
