micronaut:
  application:
    name: availability
mongodb:
  uri: ${MONGO_PROTOCOL:mongodb}://${MONGO_CREDENTIALS:}${MONGO_HOST:`localhost:27017`}
  automatic-class-models: false
grpc:
  server:
    port: ${SERVER_PORT:8081}
  channels:
    users:
      address: ${USERS_HOST:localhost}:${USERS_PORT:8080}
      plaintext: true
