micronaut:
  application:
    name: availability
  server:
    port: ${MANAGEMENT_PORT:8181}
mongodb:
  uri: ${MONGO_PROTOCOL:mongodb}://${MONGO_CREDENTIALS:}${MONGO_HOST:`localhost:27017`}
  automatic-class-models: false
grpc:
  server:
    port: ${SERVER_PORT:8081}
  channels:
    users:
      address: ${USERS_SERVICE_HOST:`users:50051`}
      plaintext: true
